site_name: Documentación Keycloack
site_url: https://kan.com.ar/
nav:
  - Home: index.md
  - realms/index.md
    - ../configuration.md

markdown_extensions:
  - admonition # Extension para hacer notas y tips
  - pymdownx.details
  - pymdownx.superfences
  - def_list #Extension para hacer listas ordenadas

theme:
  name: 'material'
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
  features:
    - search.suggest

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: es
          default: true
          name: Español
          build: true

extra:
  homepage: https://kan.com.ar
  analytics:
    provider: google
    property: G-Z1CERXCTNQ
  alternate:
    - name: Español
      lang: es
      link: es/

repo_url: https://github.com/Kan-T-IT/keycloack-documentation


  
